INSERT INTO Groups(Name)
VALUES ('Myrshite')
INSERT INTO Groups(Name)
VALUES ('Slabacite')
INSERT INTO Users(Username,Pass,FullName,LastLoginTime, GroupId)
VALUES ('Miro','mirkata','123456','1234-1-1', 1)
INSERT INTO Users(Username,Pass,FullName,LastLoginTime, GroupId)
VALUES ('Pepa','mastiqta','123456','1994-1-1', 2)
INSERT INTO Users(Username,Pass,FullName,LastLoginTime, GroupId)
VALUES ('Kiro','omotnika','000000','2004-1-1', 3)